name = "overlay"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52e5b94aecfe7a4015b0ad1402bfdedcfa3ef8cd06d8009624629db6cb007682"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
