#disable those optional mixins if it breaks something
#set to true to disable otherwise apply
noPatternEncodingMixin=false
noFixTossBug=false
noRecipeFilterForDualHatch=false
noRemoveUnusedCacheInModularUIContainer=false
addEUCraftingMixins=false
noAEItemSortMixins=false
