#This file stores configuration options for AngelicaShaders, such as the currently active shaderpack
#Sun May 10 20:01:51 CDT 2026
disableUpdateMessage=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
